<?php

namespace Database\Seeders;

use App\Models\Proveedor;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class ProveedorSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $this->proveetor("Arte regal", "Arte Regal es una empresa especializada en la distribución de artículos para el hogar, decoración y menaje, ofreciendo productos de calidad con diseños únicos y a precios competitivos.", null, null, null, "\img/marcas-logos/arteRegal-logo.png", null);
        $this->proveetor("Euro Quimica", "Euroquímica S.A. es una empresa española con más de 50 años de trayectoria, especializada en la fabricación y comercialización de productos de limpieza para el hogar y uso profesional. Con plantas de producción en Illescas (Toledo) y Zaragoza, destaca por marcas emblemáticas como Lagarto, Alpes y Purex. Su compromiso con la sostenibilidad y la innovación le permite ofrecer soluciones eficaces y adaptadas a las necesidades de los consumidores, tanto a nivel nacional como internacional", null, null, null, "\img/marcas-logos/euroquimica-logo.png", null);
        $this->proveetor("Soudal", "Soudal es una empresa familiar belga fundada en 1966 por Vic Swerts, reconocida como el mayor fabricante europeo independiente de selladores, adhesivos y espumas de poliuretano para profesionales y particulares. Con sede en Turnhout, Bélgica, Soudal opera en más de 140 países y cuenta con 29 centros de producción en cinco continentes, empleando a más de 4.000 personas a nivel mundial.", null, null, null, "\img/marcas-logos/soudal-logo.png", null);
        $this->proveetor("Pons Quimicas", "Pons Químicas S.L. es una empresa consolidada y en constante crecimiento, establecida en Xàbia (Alicante) desde 1960. Se dedica a la fabricación y desarrollo de productos de limpieza para el hogar e insecticidas, ofreciendo calidad y versatilidad a sus clientes mediante procesos automatizados de producción que alcanzan los 22.000 litros por hora.", null, null, null, "\img/marcas-logos/ponsQuimicas-logo.png", null);
        $this->proveetor("Grupo Cuatrogasa",  "Grupo Cuatrogasa es una empresa sevillana especializada en la fabricación y comercialización de productos de higiene, protección y limpieza, tanto para el hogar como para el sector profesional. Fundada en 1985, ofrece soluciones en guantes de protección, útiles de limpieza, conservación de alimentos y vestuario desechable. Su catálogo abarca desde guantes desechables hasta productos para la conservación de alimentos, adaptados a las necesidades de sectores como el sanitario, HORECA (hoteles, restaurantes y cafeterías), la industria y la limpieza profesional.", null, null, null, "\img/marcas-logos/grupoCuatrogasa-logo.png", null);
        $this->proveetor("Ac marca", "AC Marca es un grupo empresarial español con más de 100 años de historia, especializado en la fabricación y comercialización de productos de consumo en los sectores de cuidado del hogar, cuidado personal, dermocosmética y bricolaje. Fundado en 1922 con la marca de tintes Iberia, ha diversificado su actividad incorporando marcas reconocidas como Norit, Sanytol, Lactovit, Ceys, Giorgi, Ecran y Orion. Con sede en Barcelona, cuenta con 13 filiales propias, más de 1.100 empleados y presencia en más de 70 países. Su enfoque se basa en la innovación, la internacionalización y la consolidación de marcas de confianza para el consumidor.", null, null, null, "\img/marcas-logos/acmarca-logo.jpeg", null);
        $this->proveetor("Essity", "Essity es una empresa multinacional sueca líder en productos de higiene y salud, con presencia en más de 150 países. Fabrica y comercializa soluciones para el cuidado personal (TENA, Libresse), papel para el hogar (Colhogar, Tempo) y limpieza profesional (Tork), destacando por su enfoque en sostenibilidad e innovación.", null, null, null, "\img/marcas-logos/essity-logo.png", null);
        $this->proveetor("Palboplast", "Palboplast S.A. es una empresa española fundada en 1987, especializada en la fabricación de bolsas de basura elaboradas con plástico 100% reciclado. Con sede en Valencia, destaca por su compromiso con la sostenibilidad y la innovación, ofreciendo productos de alta calidad tanto para el uso doméstico como profesional. Forma parte del Grupo Soria y cuenta con una capacidad de producción de 400 toneladas mensuales, exportando parte de su producción a varios países europeos.", null, null, null, "\img/marcas-logos/palboplast-logo.png", null);
        $this->proveetor("MakroPlast", "Makroplas S.L. es una empresa española fundada en 1994 y ubicada en Olmedo (Valladolid), especializada en la fabricación de productos plásticos flexibles como bolsas, sacos y film termo-retráctil. Comprometida con la sostenibilidad, utiliza materiales 100% reciclables y naturales, ofreciendo soluciones personalizadas para diversos sectores. Con instalaciones de 20.000 m² y laboratorio propio, Makroplas destaca por su enfoque en la calidad, respaldado por certificaciones como la ISO 9001:2015 y la norma BRC para envases y materiales de envasado. Su crecimiento sostenido y presencia internacional la posicionan como un referente en innovación y responsabilidad medioambiental en la industria del plástico flexible.", null, null, null, "\img/marcas-logos/makroplas-logo.png", null);
        $this->proveetor("Instituto Español", "Instituto Español S.A. es una empresa andaluza con sede en Hinojos (Huelva), fundada en 1903, especializada en la fabricación de productos de perfumería, cosmética e higiene personal. Con más de 120 años de trayectoria, la compañía ha consolidado marcas emblemáticas como Gotas de Oro, Ánfora y Gotas Frescas, y ha expandido su presencia internacional, exportando a más de 68 países. Comprometida con la sostenibilidad y la innovación, Instituto Español mantiene una plantilla de aproximadamente 220 empleados, de los cuales el 95% son mujeres, y continúa siendo un referente en el sector gracias a su enfoque en la calidad y el respeto al medio ambiente.", null, null, null, "\img/marcas-logos/institutoEspañol-logo.jpg", null);
        $this->proveetor("Goma camps", "Gomà-Camps es una empresa familiar española con más de 265 años de historia, especializada en la fabricación y comercialización de papel tisú y soluciones afines. Con sede en La Riba (Tarragona), produce anualmente alrededor de 60.000 toneladas de papel, incluyendo papel higiénico, servilletas, toallas de papel y manteles, dirigidos a sectores como hostelería, salud y limpieza profesional. La compañía destaca por su compromiso con la sostenibilidad, ofreciendo productos elaborados con celulosa virgen de cultivos controlados y papel reciclado, como su gama GC ecologic+, certificada por ECOLABEL y FSC. Además, Gomà-Camps ha sido pionera en lanzar productos con envases compostables, reforzando su apuesta por la economía circular y el respeto al medio ambiente.", null, null, null, '\img/marcas-logos/gomacamps-logo.jpeg', null);
        $this->proveetor("Loreal", "L’Oréal es una empresa multinacional francesa fundada en 1909 por el químico Eugène Schueller, inicialmente centrada en la creación de tintes capilares seguros. Con sede en Clichy, cerca de París, se ha consolidado como la mayor compañía de cosméticos del mundo, operando en más de 150 países. Su portafolio abarca productos para el cuidado del cabello, la piel, maquillaje y perfumes, con marcas reconocidas como L’Oréal Paris, Maybelline, Garnier, Lancôme, Vichy y La Roche-Posay. La empresa se estructura en cuatro divisiones: Productos Profesionales, Productos de Consumo, L’Oréal Luxe y Cosmética Activa. Además, L’Oréal lidera la innovación tecnológica en el sector mediante su estrategia de 'Beauty Tech', desarrollando herramientas como probadores virtuales y dispositivos inteligentes, y mantiene un firme compromiso con la sostenibilidad y la inclusión.", null, null, null, '\img/marcas-logos/loreal-logo.png', null);
        $this->proveetor("Beiersdorf", "Beiersdorf AG es una multinacional alemana especializada en productos de cuidado personal y adhesivos, con sede en Hamburgo. Fundada en 1882 por Paul C. Beiersdorf, la empresa es reconocida por marcas líderes como NIVEA, Eucerin, La Prairie, Labello, Hansaplast y Tesa. Opera en más de 160 países y cuenta con aproximadamente 20.000 empleados a nivel mundial. Beiersdorf se estructura en dos segmentos principales: el de consumo, enfocado en productos de cuidado de la piel, y Tesa, dedicado a soluciones adhesivas para la industria y el hogar. Su compromiso con la innovación y la sostenibilidad la posiciona como una de las compañías más influyentes en el sector del cuidado personal a nivel global.", null, null, null, '\img/marcas-logos/Beiersdorf-logo.webp', null);
        $this->proveetor("Quimunsa", "Quimunsa (Química de Munguía S.A.) es una empresa española líder en el desarrollo, fabricación y comercialización de soluciones biocidas para el control de plagas y la sanidad ambiental. Con sede en Mungia (Bizkaia), la compañía cuenta con más de 60 años de experiencia y una amplia gama de productos que incluyen insecticidas, raticidas, desinfectantes y protectores para la madera.", null, null, null, '\img/marcas-logos/quimunsa-logo.png', null);
        $this->proveetor("Vetusplas", "Vetusplas S.L. es una empresa asturiana fundada en 1998, especializada en la distribución mayorista de productos de plástico para el hogar, menaje, jardinería, droguería, juguetería y bisutería. Con sede en Llanera, Asturias, la compañía se enfoca en ofrecer productos de calidad y servicio a comercios del sector, principalmente almacenes de jardinería. Aunque su actividad se concentra en el mercado nacional, Vetusplas mantiene un catálogo diverso y un compromiso con la excelencia en el servicio al por mayor.", null, null, null, "\img/marcas-logos/vetusplas-logo.png", null);
        $this->proveetor("Zelnova Zeltia", "Zelnova Zeltia es una empresa española especializada en la fabricación y comercialización de productos para el hogar, jardín y cuidado personal. Nació el 30 de diciembre de 1991 como escisión de Cooper Zeltia, S.A., heredando la actividad de fabricación y comercialización de productos químicos que comenzó Zeltia, S.A. en 1939.", null, null, null, "\img/marcas-logos/zelnovaZeltia-logo.jpg", null);
        // Proveedor::factory(10)->create();
    }

    public function proveetor (string $nombre, ?string $descripcion,  ?string $email, ?string $telefono, ?string $direccion, ?string $logo_url, ?string $img_url) {
        Proveedor::create([
            'nombre' => $nombre,
            'descripcion' => $descripcion,
            'email' => $email,
            'telefono' => $telefono,
            'direccion' => $direccion,
            'logo_url' => $logo_url,
            'img_url' => $img_url
        ]);
    }
}
